#!/bin/bash

# shellcheck disable=SC1091
[ -f /etc/bash_completion ] && source /etc/bash_completion

if [ -d ~/.bashrc.d/opt ]; then
	for i in ~/.bashrc.d/opt/*; do
		# shellcheck disable=SC1090
		source "$i"
	done
fi

if [ -d ~/.bashrc.d/dist ]; then
	for i in ~/.bashrc.d/dist/*; do
		# shellcheck disable=SC1090
		source "$i"
	done
fi

ulimit -c unlimited

export EDITOR=/usr/bin/vim
export HISTCONTROL=ignoredups
export HISTFILESIZE=10000
export HISTSIZE=10000
export HISTIGNORE="gpb:gvl:gss:ls:bg:fg:disown:ls -l:cd: *"
export PATH=$PATH:~/bin/

# belongs in go setup recipe
#export PATH=$PATH:/opt/go/bin:~/go/bin

alias ls="ls --color"

unset SESSION_MANAGER
